### ISSUE TITLE
Autoslot does not work with type hints

### ISSUE THREAD

**Issue by spacemanspiff2007** [cjrh/autoslot#2]
Hi,

I really like the idea of autoslot.
However, I have lot's of type hints in my code which are currently not picked up properly.
It would be really nice if you could make this work, too.

```python
import autoslot
class test_hint(autoslot.Slots):
    def __init__(self):
        self.a = 0
        self.b : int

test = test_hint()
test.a = 1 # ok
test.b = 1 # <-- this fails!
```

**Comment by cjrh** [comment]
Cool idea!

The way autoslot works is that an internal metaclass reads the actual, compiled bytecode of the `__init__()` method to look for all assignments to attributes of self. It's really quite crude internally. 

IF there is a recognizable way of seeing the type hint in the bytecode, then it will be easy to add this feature. Unfortunately, it appears as though the type hint doesn't make it to the bytecode:

```
>>> import dis
>>> dis.dis(test_hint)
Disassembly of __init__:
  3           0 LOAD_CONST               1 (0)
              2 LOAD_FAST                0 (self)
              4 STORE_ATTR               0 (a)

  4           6 LOAD_FAST                0 (self)
              8 POP_TOP
             10 LOAD_CONST               0 (None)
             12 RETURN_VALUE

```
Only `a` appears in the disassembled output, not `b`.

**Comment by cjrh** [comment]
It would however be possible to obtain type annotations if they're made at the class scope, which is how `dataclasses` does it:

```
>>> class test_hint():
...   c: int
...   def __init__(self):
...     self.a = 1
...     self.b : int
...
>>> test_hint.__annotations__
{'c': <class 'int'>}
```
Of course, one would need to verify if the information about annotations is available during metaclass invocation (the actual `test_hint` class is not yet constructed when the metaclass runs, in fact the metaclass _returns_ the fully-constructed `test_hint` class).

**Comment by spacemanspiff2007** [comment]
That's a shame! But thank you for the quick reply!

**Comment by cjrh** [comment]
@spacemanspiff2007 Strictly speaking, your `b`, declared as `int` is **not** an int if you don't assign an int. I propose that a better type signature for your `b` is `Optional[int]`, and then you can assign `None`. This will both make the type signature correct once again, _and_ make `autoslot` work again:

```
import autoslot
class test_hint(autoslot.Slots):
    def __init__(self):
        self.a = 0
        self.b: Optional[int] = None
```

Is this a solution for you? I would be interested to know if there is a specific reason why you might want to intentionally leave `b` unassigned.

**Comment by cjrh** [comment]
Yes, and the code would work exactly the same. But the type signature would be inaccurate because `None` does not have type `int`. The more accurate type hint is `self.b: Union[int, None] = None` to indicate that `b` can be both `None` and `int`, but of course we already have a shortcut for that, which is `Optional` :)

But it's your code, you can do what you want ;)

**Comment by spacemanspiff2007** [comment]
Ah nice - I learned something again. Thank you.
